Repository ros/ros_comm, pull requests merged in 2018-08, with the labels that each got.

#1451 Throw BagException when disk is full
  tools/rosbag/src/recorder.cpp
Labels: enhancement

#1464 Add hasStarted() const to Timer API
  clients/roscpp/include/ros/timer.h
  clients/roscpp/src/libros/timer.cpp
Labels: enhancement

#1442 Fix for issue 1441
  clients/rospy/src/rospy/impl/rosout.py
Labels: enhancement

#1473 fix regressions from 1372
  tools/rosbag/src/rosbag/bag.py
Labels: bug, hitlist

#1425 Disable rosout.log by using environment variable
  tools/rosout/rosout.cpp
Labels: enhancement

#1489 topic_tools/mux: add ~latch option
  tools/topic_tools/src/mux.cpp
Labels: enhancement

#1486 fix topic_tools environment hook
  tools/topic_tools/env-hooks/20.transform.bash
Labels: bug

#1479 Fix test code build issues on Windows
  utilities/xmlrpcpp/include/xmlrpcpp/XmlRpcUtil.h
  utilities/xmlrpcpp/test/CMakeLists.txt
  utilities/xmlrpcpp/test/mock_socket.cpp
  utilities/xmlrpcpp/test/test_client.cpp
  utilities/xmlrpcpp/test/test_dispatch.cpp
  utilities/xmlrpcpp/test/test_dispatch_live.cpp
  utilities/xmlrpcpp/test/test_ulimit.cpp
Labels: enhancement

#1483 Fix message_filters build issue on the template syntax
  utilities/message_filters/include/message_filters/sync_policies/exact_time.h
Labels: enhancement

#1476 [roslaunch] Better exception handling when resource is not found.
  tools/roslaunch/src/roslaunch/xmlloader.py
Labels: enhancement

#1497 show connection info on rosnode info
  clients/rospy/src/rospy/impl/tcpros_base.py
  tools/rosnode/src/rosnode/__init__.py
Labels: enhancement
