Repository ros/ros_comm, pull requests merged in 2018-06, with the labels that each got.

#1416 Fix Issue 1346 - Make a copy of the topic list
  clients/rospy/src/rospy/topics.py
Labels: bug, consider-backport

#1424 import rosbag locally instead of at module level
  tools/rosmsg/src/rosmsg/__init__.py
Labels: enhancement

#1415 Fix some errors in some probably not frequented code paths melodic
  clients/rospy/src/rospy/impl/tcpros_pubsub.py
  clients/rospy/src/rospy/names.py
Labels: bug, consider-backport

#1421 Fix some errors in some probably not frequented code paths kinetic
  clients/rospy/src/rospy/impl/tcpros_pubsub.py
  clients/rospy/src/rospy/impl/tcpros_service.py
  clients/rospy/src/rospy/names.py
Labels: consider-backport
