Repository ros/ros_comm, pull requests merged in 2018-04, with the labels that each got.

#1354 Add substitution when loading yaml files
  tools/roslaunch/src/roslaunch/loader.py
  tools/roslaunch/src/roslaunch/xmlloader.py
  tools/roslaunch/test/params_subst.yaml
  tools/roslaunch/test/unit/test_xmlloader.py
  tools/roslaunch/test/xml/test-rosparam-valid.xml
Labels: enhancement

#1154 Created public get_topic_list() function for use in other scripts.
  tools/rostopic/src/rostopic/__init__.py
  tools/rostopic/test/test_rostopic.py
Labels: enhancement, hitlist, requires-changes

#1295 rosbag record: Add TransportHint options --tcpnodelay and --udp
  tools/rosbag/include/rosbag/recorder.h
  tools/rosbag/src/record.cpp
  tools/rosbag/src/recorder.cpp
  tools/rosbag/src/rosbag/rosbag_main.py
Labels: consider-future-release, enhancement

#1241 added parameter to stop client libraries from generating topics list
  clients/roscpp/include/ros/rosout_appender.h
  clients/roscpp/src/libros/rosout_appender.cpp
  clients/rospy/src/rospy/impl/rosout.py
Labels: consider-future-release, hitlist

#1287 Use HTTP/1.1 in XMLRPC Server
  tools/rosgraph/src/rosgraph/xmlrpc.py
Labels: enhancement, hitlist

#1365 Replaced Double-Checked Locking pattern with static variable. Fixes #1364
  clients/roscpp/src/libros/connection_manager.cpp
  clients/roscpp/src/libros/poll_manager.cpp
  clients/roscpp/src/libros/xmlrpc_manager.cpp
Labels: consider-backport

#1130 add time when timer expired to timer events
  clients/roscpp/include/ros/forwards.h
  clients/roscpp/include/ros/timer_manager.h
  clients/roscpp/src/libros/steady_timer.cpp
  test/test_roscpp/test/src/timer_callbacks.cpp
Labels: consider-future-release, hitlist

#1206 Implement Bag encryption/decryption.
  tools/rosbag/CMakeLists.txt
  tools/rosbag/package.xml
  tools/rosbag/src/encrypt.cpp
  tools/rosbag/src/rosbag/bag.py
  tools/rosbag/src/rosbag/rosbag_main.py
  tools/rosbag_storage/CMakeLists.txt
  tools/rosbag_storage/encryptor_plugins.xml
  tools/rosbag_storage/include/rosbag/bag.h
  tools/rosbag_storage/include/rosbag/constants.h
  tools/rosbag_storage/include/rosbag/encryptor.h
  tools/rosbag_storage/package.xml
  tools/rosbag_storage/src/aes_encryptor.cpp
  tools/rosbag_storage/src/bag.cpp
  tools/rosbag_storage/src/encryptor.cpp
  tools/rosbag_storage/test/test_aes_encryptor.cpp
Labels: consider-future-release, enhancement, hitlist

#1372 keep connection header information in rosbag operations (#679, #685)
  tools/rosbag/src/rosbag/bag.py
  tools/rosbag/src/rosbag/rosbag_main.py
Labels: hitlist

#1374 Specialize BagCallbackT for MessageInstance
  test/test_rosbag_storage/CMakeLists.txt
  test/test_rosbag_storage/src/bag_player.cpp
  tools/rosbag_storage/include/rosbag/bag_player.h
Labels: hitlist
