Repository ros/ros_comm, pull requests merged in 2019-01, with the labels that each got.

#1541 Removed nullptr access from Timer().hasStarted()
  clients/roscpp/include/ros/timer.h
Labels: bug, consider-backport

#1596 query ipv6 only if specified
  utilities/roswtf/src/roswtf/network.py
Labels: enhancement

#1595 Fix race due unprotected access to callbacks_ in roscpp client
  clients/roscpp/src/libros/publication.cpp
Labels: bug

#1573 Added dependencies and Docker container alerts to manual test. Fixes #1567
  test/test_roscpp/test/scripts/test_udp_with_dropped_packets.sh
Labels: enhancement

#1601 fix various test problems
  test/test_rostest/CMakeLists.txt
  test/test_rostest/package.xml
  test/test_rostest/test/just_advertise
  test/test_rostest/test/publishtest.test
  test/test_rostest/test_nodes/talker.py
  tools/rosbag_storage/CMakeLists.txt
  tools/rosbag_storage/package.xml
  tools/rosgraph/test/test_roslogging.py
  tools/rosgraph/test/test_roslogging_user_logger.py
  tools/roslaunch/test/unit/test_nodeprocess.py
  tools/roslaunch/test_nodes/talker.py
  tools/rostest/CMakeLists.txt
  tools/rostest/test/hztest.test
  tools/rostest/test_nodes/talker.py
Labels: bug

#1565 Add hasStarted() const to WallTimer and SteadyTimer API
  clients/roscpp/include/ros/steady_timer.h
  clients/roscpp/include/ros/wall_timer.h
  clients/roscpp/src/libros/steady_timer.cpp
  clients/roscpp/src/libros/wall_timer.cpp
Labels: enhancement

#1438 remove messages that are newer than the newly added message
  utilities/message_filters/src/message_filters/__init__.py
  utilities/message_filters/test/test_approxsync.py
Labels: enhancement

#1540 roslaunch/xmlloader: use continue instead of pass for args_only
  tools/roslaunch/src/roslaunch/xmlloader.py
Labels: enhancement
