Repository ros/ros_comm, pull requests merged in 2019-03, with the labels that each got.

#1645 roscpp/TopicManager: avoid deadlock
  clients/roscpp/src/libros/topic_manager.cpp
Labels: bug

#1635 rostopic: repeatedly republish message from file
  tools/rostopic/src/rostopic/__init__.py
Labels: enhancement

#1653 #1455 reviseted: make roslaunch-check respect arg remappings with command line argument
  tools/roslaunch/resources/example.launch
  tools/roslaunch/src/roslaunch/depends.py
Labels: enhancement

#1655 #1468 revisited: add option to hide summary from roslaunch output.
  tools/roslaunch/src/roslaunch/__init__.py
  tools/roslaunch/src/roslaunch/parent.py
Labels: enhancement

#1639 Fix wrong error handling in migration.
  tools/rosbag/src/rosbag/migration.py
Labels: enhancement

#1659 rostest: use AnyMsg in publishtest
  tools/rostest/CMakeLists.txt
  tools/rostest/nodes/publishtest
  tools/rostest/test/publishtest.test
Labels: enhancement

#1499 fix #1474 move bag encryption plugins into separate library
  tools/rosbag_storage/CMakeLists.txt
  tools/rosbag_storage/encryptor_plugins.xml
  tools/rosbag_storage/include/rosbag/aes_encryptor.h
  tools/rosbag_storage/include/rosbag/encryptor.h
  tools/rosbag_storage/include/rosbag/gpgme_utils.h
  tools/rosbag_storage/include/rosbag/no_encryptor.h
  tools/rosbag_storage/src/aes_encryptor.cpp
  tools/rosbag_storage/src/gpgme_utils.cpp
  tools/rosbag_storage/src/no_encryptor.cpp
  tools/rosbag_storage/test/test_aes_encryptor.cpp
Labels: bug, enhancement
