Repository ros/ros_comm, pull requests merged in 2020-05, with the labels that each got.

#1948 [noetic] Avoid infinite recursion in rosrun tab completion when rosbash is not installed
  tools/topic_tools/env-hooks/20.transform.bash
Labels: bug, consider-backport

#1544 roscpp: Multiple latched publishers per process on the same topic (fix #146)
  clients/roscpp/include/ros/forwards.h
  clients/roscpp/include/ros/publication.h
  clients/roscpp/include/ros/publisher.h
  clients/roscpp/src/libros/node_handle.cpp
  clients/roscpp/src/libros/publication.cpp
  clients/roscpp/src/libros/publisher.cpp
  clients/roscpp/src/libros/topic_manager.cpp
  test/test_roscpp/test/CMakeLists.txt
  test/test_roscpp/test/launch/multiple_latched_publishers.xml
  test/test_roscpp/test/src/CMakeLists.txt
  test/test_roscpp/test/src/multiple_latched_publishers.cpp
Labels: enhancement

#1952 Fix bag migration failures caused by typo in connection_header assignment
  tools/rosbag/src/rosbag/migration.py
Labels: bug

#1850 Add option to repeat latched messages at the start of bag splits
  tools/rosbag/include/rosbag/recorder.h
  tools/rosbag/src/record.cpp
  tools/rosbag/src/recorder.cpp
  tools/rosbag/src/rosbag/rosbag_main.py
Labels: enhancement

#1937 roslaunch: Allow passing _TIMEOUT_SIGINT and _TIMEOUT_SIGTERM as parameters
  tools/roslaunch/resources/timeouts.launch
  tools/roslaunch/scripts/roscore
  tools/roslaunch/src/roslaunch/__init__.py
  tools/roslaunch/src/roslaunch/child.py
  tools/roslaunch/src/roslaunch/launch.py
  tools/roslaunch/src/roslaunch/nodeprocess.py
  tools/roslaunch/src/roslaunch/parent.py
  tools/roslaunch/src/roslaunch/remote.py
  tools/roslaunch/src/roslaunch/remoteprocess.py
  tools/roslaunch/src/roslaunch/server.py
  tools/roslaunch/test/manual-test-remote-timeouts.sh
  tools/roslaunch/test/signal_logger.py
  tools/roslaunch/test/unit/test_nodeprocess.py
  tools/roslaunch/test/unit/test_roslaunch_parent.py
  tools/roslaunch/test/xml/manual-test-remote-timeouts.launch
Labels: enhancement, requires-changes

#1940 Fix bug that connection drop signal related funtion throw a bad_weak …
  clients/roscpp/include/ros/transport_publisher_link.h
  clients/roscpp/src/libros/connection.cpp
  clients/roscpp/src/libros/service_server_link.cpp
  clients/roscpp/src/libros/transport_publisher_link.cpp
  clients/roscpp/src/libros/transport_subscriber_link.cpp
Labels: bug

#1954 check if async socket connect is success or failure before read and write in TransportT
  clients/roscpp/include/ros/io.h
  clients/roscpp/include/ros/transport/transport_tcp.h
  clients/roscpp/src/libros/io.cpp
  clients/roscpp/src/libros/transport/transport_tcp.cpp
Labels: bug, consider-future-release

#1950 Fix a bug that using a destroyed connection object.
  clients/roscpp/src/libros/connection.cpp
Labels: bug, consider-backport

#1965 fix NameError in launch error handling
  tools/roslaunch/src/roslaunch/__init__.py
Labels: bug, consider-backport

#1961 [noetic] Fixing Windows build break.
  clients/roscpp/src/libros/io.cpp
Labels: bug
