Repository ros/ros_comm, pull requests merged in 2020-07, with the labels that each got.

#1944 Add latch param to throttle
  tools/topic_tools/src/throttle.cpp
Labels: enhancement

#1991 Allow mixing latched and unlatched publishers.
  clients/roscpp/include/ros/publication.h
  clients/roscpp/src/libros/publication.cpp
  clients/roscpp/src/libros/topic_manager.cpp
  test/test_roscpp/test/src/multiple_latched_publishers.cpp
Labels: bug

#1983 Changed is_async_connected to use epoll when available
  clients/roscpp/src/libros/io.cpp
Labels: enhancement

#2007 remove not existing NodeProxy from rospy __all__
  clients/rospy/src/rospy/__init__.py
Labels: bug, consider-backport

#1932 Use an internal implementation of boost::condition_variable with monotonic clock
  clients/roscpp/CMakeLists.txt
  clients/roscpp/include/ros/callback_queue.h
  clients/roscpp/include/ros/internal/condition_variable.h
  clients/roscpp/include/ros/rosout_appender.h
  clients/roscpp/include/ros/service_server_link.h
  clients/roscpp/include/ros/timer_manager.h
  clients/roscpp/include/ros/transport/transport.h
Labels: bug, hitlist

#2013 use range instead of xrange
  tools/rostopic/src/rostopic/__init__.py
Labels: bug

#1684 #1608 revisited: Fix subscription busy wait melodic
  clients/roscpp/src/libros/callback_queue.cpp
  clients/roscpp/src/libros/subscription_queue.cpp
  test/test_roscpp/test/fake_message.h
  test/test_roscpp/test/test_callback_queue.cpp
  test/test_roscpp/test/test_subscription_queue.cpp
Labels: bug, consider-backport, hitlist
