Repository ros/ros_comm, pull requests merged in 2020-02, with the labels that each got.

#1854 Fix (#1516), prevent indefinitely trapping in unknown error state
  tools/rosnode/src/rosnode/__init__.py
Labels: bug

#1876 [Windows][melodic-devel] Conditionally guard sys/socket.h for Windows.
  clients/roscpp/src/libros/transport/transport_tcp.cpp
  clients/roscpp/src/libros/transport/transport_udp.cpp
Labels: bug

#1813 Wrap file names in quotes so they can be click selected in terminal
  tools/rosbag/src/recorder.cpp
Labels: enhancement

#1877 test_rosbag: add target dependency to fix unit test failures in parallel builds
  test/test_rosbag/bag_migration_tests/CMakeLists.txt
Labels: bug

#1826 Allowed empty ssh password for remote launching
  tools/roslaunch/src/roslaunch/core.py
  tools/roslaunch/src/roslaunch/remoteprocess.py
Labels: enhancement

#1872 [windows] Workaround for Python 2 xmlrpc performance issues.
  tools/roslaunch/env-hooks/10.roslaunch.bat
Labels: bug

#1860 Add overload of ApproximateTime::setInterMessageLowerBound() to set all topics to the same value
  utilities/message_filters/include/message_filters/sync_policies/approximate_time.h
  utilities/message_filters/test/test_approximate_time_policy.cpp
Labels: enhancement

#1858 roscpp: disable rosout via ROSCPP_NO_ROSOUT env var
  clients/roscpp/src/libros/init.cpp
Labels: enhancement

#1809 add platform check for roslaunch --args code path
  tools/roslaunch/src/roslaunch/node_args.py
Labels: bug

#1878 Drop custom implementation of boost::condition_variable to fix busy-wait spinning
  clients/roscpp/CMakeLists.txt
  clients/roscpp/include/boost_161_condition_variable.h
  clients/roscpp/include/boost_161_pthread_condition_variable.h
  clients/roscpp/include/boost_161_pthread_condition_variable_fwd.h
  clients/roscpp/include/ros/callback_queue.h
  clients/roscpp/include/ros/rosout_appender.h
  clients/roscpp/include/ros/service_server_link.h
  clients/roscpp/include/ros/timer_manager.h
  clients/roscpp/src/libros/callback_queue.cpp
  clients/roscpp/src/libros/internal_timer_manager.cpp
  clients/roscpp/src/libros/steady_timer.cpp
Labels: bug, hitlist

#1515 rospy: added get_param_cached
  clients/rospy/src/rospy/__init__.py
  clients/rospy/src/rospy/client.py
  clients/rospy/src/rospy/impl/paramserver.py
  clients/rospy/src/rospy/msproxy.py
Labels: enhancement

#1788 [roslaunch] Add ignore default args option to roslaunch-check
  tools/roslaunch/cmake/roslaunch-extras.cmake.em
  tools/roslaunch/scripts/roslaunch-check
  tools/roslaunch/src/roslaunch/config.py
  tools/roslaunch/src/roslaunch/depends.py
  tools/roslaunch/src/roslaunch/rlutil.py
  tools/roslaunch/src/roslaunch/xmlloader.py
  tools/roslaunch/test/unit/test_roslaunch_rlutil.py
  tools/roslaunch/test/xml/test-ignore-unset-args.launch
Labels: enhancement

#1663 #1470 revisited: Use node namespace when looking up topic
  tools/topic_tools/CMakeLists.txt
  tools/topic_tools/scripts/transform
  tools/topic_tools/test/test_transform.py
  tools/topic_tools/test/transform.test
Labels: bug

#1290 Simplified internal loggers
  clients/rospy/src/rospy/core.py
Labels: enhancement

#1289 Added args and kwargs to rospy.log*
  clients/rospy/src/rospy/core.py
Labels: enhancement

#1810 wrap env prefix with double quotes
  tools/roslaunch/src/roslaunch/node_args.py
Labels: bug

#1882 [windows][melodic] portable duration cast patch to #1878
  clients/roscpp/include/ros/timer_manager.h
Labels: bug

#1881 Use cached parameter for rosout_disable_topics_generation
  clients/rospy/src/rospy/impl/rosout.py
Labels: bug

#1868 Do not display error message if poll yields EINTR
  clients/roscpp/src/libros/poll_set.cpp
Labels: enhancement

#1471 Reuse xmlrpc connections everywhere
  clients/rospy/src/rospy/core.py
  clients/rospy/src/rospy/impl/masterslave.py
  clients/rospy/src/rospy/msproxy.py
Labels: bug, enhancement, requires-changes

#1789 [kinetic] Added rosbag::Bag::isOpen
  tools/rosbag_storage/include/rosbag/bag.h
  tools/rosbag_storage/src/bag.cpp
Labels: enhancement

#1869 Bump CMake version to avoid CMP0048 warning
  clients/roscpp/CMakeLists.txt
  clients/rospy/CMakeLists.txt
  ros_comm/CMakeLists.txt
  test/test_rosbag/CMakeLists.txt
  test/test_rosbag_storage/CMakeLists.txt
  test/test_roscpp/CMakeLists.txt
  test/test_rosgraph/CMakeLists.txt
  test/test_roslaunch/CMakeLists.txt
  test/test_roslib_comm/CMakeLists.txt
  test/test_rosmaster/CMakeLists.txt
  test/test_rosparam/CMakeLists.txt
  test/test_rospy/CMakeLists.txt
  test/test_rosservice/CMakeLists.txt
  test/test_rostest/CMakeLists.txt
  test/test_rostopic/CMakeLists.txt
  tools/rosbag/CMakeLists.txt
  tools/rosbag_storage/CMakeLists.txt
  tools/rosgraph/CMakeLists.txt
  tools/roslaunch/CMakeLists.txt
  tools/rosmaster/CMakeLists.txt
  tools/rosmsg/CMakeLists.txt
  tools/rosnode/CMakeLists.txt
  tools/rosout/CMakeLists.txt
  tools/rosparam/CMakeLists.txt
  tools/rosservice/CMakeLists.txt
  tools/rostest/CMakeLists.txt
  tools/rostopic/CMakeLists.txt
  tools/topic_tools/CMakeLists.txt
  utilities/message_filters/CMakeLists.txt
  utilities/roslz4/CMakeLists.txt
  utilities/roswtf/CMakeLists.txt
  utilities/xmlrpcpp/CMakeLists.txt
Labels: hitlist

#1666 #961 revisited: Add default ROS_MASTER_URI
  clients/roscpp/include/ros/init.h
  clients/roscpp/src/libros/init.cpp
  clients/roscpp/src/libros/master.cpp
  clients/rospy/src/rospy/impl/init.py
  tools/rosgraph/src/rosgraph/rosenv.py
  tools/rosgraph/test/test_rosenv.py
  utilities/roswtf/src/roswtf/context.py
Labels: enhancement

#1893 update test to pass with old and new yaml
  tools/roslaunch/test/unit/test_roslaunch_param_dump.py
Labels: bug

#1890 fix flakyness of transform test
  tools/topic_tools/test/transform.test
Labels: bug

#1894 fix dictionary changed size during iteration
  clients/rospy/src/rospy/topics.py
Labels: bug, consider-backport

#1870 Use setuptools instead of distutils
  clients/rospy/setup.py
  tools/rosbag/setup.py
  tools/rosgraph/setup.py
  tools/roslaunch/setup.py
  tools/rosmaster/setup.py
  tools/rosmsg/setup.py
  tools/rosnode/setup.py
  tools/rosparam/setup.py
  tools/rosservice/setup.py
  tools/rostest/setup.py
  tools/rostopic/setup.py
  tools/topic_tools/setup.py
  utilities/message_filters/setup.py
  utilities/roslz4/setup.py
  utilities/roswtf/setup.py
Labels: hitlist

#1895 fix missing boost dependencies
  clients/roscpp/package.xml
  utilities/message_filters/package.xml
Labels: bug

#1896 fix flakyness of test_topic_statistics
  test/test_rospy/test/rostest/test_topic_statistics.py
Labels: bug

#1897 increase time limit of advertisetest/publishtest.test to reduce flakyness
  tools/rostest/test/advertisetest.test
  tools/rostest/test/publishtest.test
Labels: bug

#1892 Add timestamp formatting for rosconsole
  tools/rosgraph/src/rosgraph/roslogging.py
  tools/rosgraph/test/test_roslogging.py
  tools/rosgraph/test/test_roslogging_user_logger.py
Labels: enhancement

#1898 export missing Boost dependency
  clients/roscpp/package.xml
Labels: bug

#1903 remove Boost version check since Noetic only targets platforms with 1.67+
  clients/roscpp/CMakeLists.txt
  tools/rosbag/src/recorder.cpp
Labels: bug
