Repository ros/ros_comm, pull requests merged in 2020-08, with the labels that each got.

#2009 Add skip_cache parameter to rosnode_ping()
  tools/rosnode/src/rosnode/__init__.py
Labels: enhancement

#2011 Use an internal implementation of boost::condition_variable with monotonic clock [kinetic-devel]
  clients/roscpp/include/boost_161_condition_variable.h
  clients/roscpp/include/boost_161_pthread_condition_variable.h
  clients/roscpp/include/boost_161_pthread_condition_variable_fwd.h
  clients/roscpp/include/ros/callback_queue.h
  clients/roscpp/include/ros/internal/condition_variable.h
  clients/roscpp/include/ros/rosout_appender.h
  clients/roscpp/include/ros/service_server_link.h
  clients/roscpp/include/ros/timer_manager.h
  clients/roscpp/include/ros/transport/transport.h
  clients/roscpp/src/libros/callback_queue.cpp
  clients/roscpp/src/libros/internal_timer_manager.cpp
  clients/roscpp/src/libros/steady_timer.cpp
Labels: bug, hitlist

#2016 [melodic] support Boost 1.66
  clients/roscpp/include/ros/internal/condition_variable.h
Labels: bug

#1284 [kinetic] Close sockets when server responds with HTTP/1.0
  clients/roscpp/src/libros/xmlrpc_manager.cpp
  utilities/xmlrpcpp/src/XmlRpcClient.cpp
Labels: enhancement

#2020 Remove 'using namespace' from condition_variable.h
  clients/roscpp/include/ros/internal/condition_variable.h
Labels: bug

#2021 [rospy] fix param cache when node is subscribing and setting a parameter
  clients/rospy/src/rospy/msproxy.py
Labels: bug

#2017 Use heapq.merge instead of custom merge sort code
  tools/rosbag/src/rosbag/bag.py
Labels: enhancement

#2023 [roscpp] Update boost::placeholders usage for boost 1.73 (and later)
  clients/roscpp/include/ros/node_handle.h
  clients/roscpp/include/ros/publisher.h
  clients/roscpp/include/ros/timer_manager.h
  clients/roscpp/include/ros/topic.h
  clients/roscpp/src/libros/connection.cpp
  clients/roscpp/src/libros/connection_manager.cpp
  clients/roscpp/src/libros/poll_set.cpp
  clients/roscpp/src/libros/service_client_link.cpp
  clients/roscpp/src/libros/service_server_link.cpp
  clients/roscpp/src/libros/topic_manager.cpp
  clients/roscpp/src/libros/transport/transport_tcp.cpp
  clients/roscpp/src/libros/transport/transport_udp.cpp
  clients/roscpp/src/libros/transport_publisher_link.cpp
  clients/roscpp/src/libros/transport_subscriber_link.cpp
  test/test_rosbag_storage/src/bag_player.cpp
  test/test_roscpp/perf/src/intra.cpp
  test/test_roscpp/test/src/multiple_subscriptions.cpp
  test/test_roscpp/test/src/pub_sub.cpp
  test/test_roscpp/test/src/publish_empty.cpp
  test/test_roscpp/test/src/publish_n_fast.cpp
  test/test_roscpp/test/src/publish_onsub.cpp
  test/test_roscpp/test/src/publish_unadvertise.cpp
  test/test_roscpp/test/src/service_adv.cpp
  test/test_roscpp/test/src/service_callback_types.cpp
  test/test_roscpp/test/src/sub_pub.cpp
  test/test_roscpp/test/src/subscribe_self.cpp
  test/test_roscpp/test/src/subscription_callback_types.cpp
  test/test_roscpp/test/test_poll_set.cpp
  test/test_roscpp/test/test_transport_tcp.cpp
  tools/rosbag/src/player.cpp
  tools/rosbag/src/recorder.cpp
  tools/rosbag_storage/src/bag.cpp
  tools/topic_tools/src/demux.cpp
  tools/topic_tools/src/mux.cpp
  utilities/message_filters/include/message_filters/cache.h
  utilities/message_filters/include/message_filters/chain.h
  utilities/message_filters/include/message_filters/pass_through.h
  utilities/message_filters/include/message_filters/signal9.h
  utilities/message_filters/include/message_filters/simple_filter.h
  utilities/message_filters/include/message_filters/subscriber.h
  utilities/message_filters/include/message_filters/synchronizer.h
  utilities/message_filters/include/message_filters/time_sequencer.h
  utilities/message_filters/test/directed.py
  utilities/message_filters/test/test_approximate_time_policy.cpp
  utilities/message_filters/test/test_simple.cpp
  utilities/message_filters/test/test_subscriber.cpp
  utilities/message_filters/test/time_sequencer_unittest.cpp
Labels: enhancement

#2025 use fully qualified ceil() in condition_variable.h
  clients/roscpp/include/ros/internal/condition_variable.h
Labels: bug
