Repository ros/ros_comm, pull requests merged in 2020-04, with the labels that each got.

#1925 Remove extra \n in ROS_DEBUG.
  clients/roscpp/src/libros/transport_subscriber_link.cpp
Labels: consider-backport

#1929 Check if enough FDs are free, instead counting the total free FDs.
  utilities/xmlrpcpp/include/xmlrpcpp/XmlRpcServer.h
  utilities/xmlrpcpp/src/XmlRpcServer.cpp
Labels: bug

#1923 Fix #923 (use undefined dynamic_lookup on OSX)
  utilities/roslz4/CMakeLists.txt
Labels: bug, consider-backport

#1922 [roslaunch] remove pycrypto import (not used)
  tools/roslaunch/src/roslaunch/remoteprocess.py
Labels: bug, consider-backport

#1934 Sort printed nodes by namespace alphabetically
  tools/roslaunch/src/roslaunch/config.py
Labels: enhancement

#1914 roslaunch-check: Search dir recursively
  tools/roslaunch/scripts/roslaunch-check
Labels: enhancement

#1518 clear message queue on simtime jumping back
  utilities/message_filters/include/message_filters/sync_policies/approximate_time.h
  utilities/message_filters/include/message_filters/sync_policies/exact_time.h
  utilities/message_filters/src/message_filters/__init__.py
  utilities/message_filters/test/test_approxsync.py
Labels: consider-future-release, enhancement

#1531 Fix negative numbers in ros statistics
  clients/roscpp/include/ros/statistics.h
  clients/roscpp/src/libros/statistics.cpp
  clients/roscpp/src/libros/subscription.cpp
Labels: bug, consider-future-release

#1722 Fix bare pointer in topic_tools::ShapeShifter
  tools/topic_tools/include/topic_tools/shape_shifter.h
  tools/topic_tools/src/shape_shifter.cpp
Labels: consider-future-release

#1924 Add rosout integration test
  test/test_rospy/CMakeLists.txt
  test/test_rospy/test/rostest/rosout.test
  test/test_rospy/test/rostest/test_rosout.py
Labels: enhancement
