Repository ros/ros_comm, pull requests merged in 2021-09, with the labels that each got.

#2131 fix bug #2123: Do not raise exception if socket is busy in TCPROSTransport
  clients/rospy/src/rospy/impl/tcpros_base.py
Labels: bug, consider-backport

#2171 fix non persistent rospy ServiceProxy is not thread-safe
  clients/rospy/src/rospy/impl/tcpros_service.py
Labels: bug, consider-backport

#2169 Fix warning related to Boost bind placeholders declared in global namespace.
  clients/roscpp/include/ros/node_handle.h
  clients/roscpp/include/ros/publisher.h
Labels: consider-backport

#2178 [rospy] add current_real docstring in timer.py
  clients/rospy/src/rospy/timer.py
Labels: enhancement, consider-backport
